### ISSUE TITLE
undefined method `table_exists?' for #

### ISSUE THREAD

**Issue by eyakcn** [technoweenie/acts_as_versioned#6]
can t figure it out, need some help

undefined method `table_exists?' for #<ActiveRecord::ConnectionAdapters::MysqlAdapter:0x48ac664>
D:/WebApp/payr/vendor/plugins/acts_as_versioned/lib/acts_as_versioned.rb:412:in`create_versioned_table'

rails 1.2.3
ps. I m trying to run the example application of ruport - payr, too many places to fix!

**Comment by technoweenie** [comment]
That method might not exist in Rails 1.2.  Try a later version.

**Comment by mkosma** [comment]
I'm getting the same error under Rails 2.3.8 (also trying to build payr)
